name: BackEndTest

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            extensions: pdo, pdo_sqlite, sqlite3, mbstring, bcmath, gd, zip

        - name: Install dependencies
          working-directory: backend
          run: |
            composer install --no-interaction --prefer-dist
            composer dump-autoload --optimize

        - name: Generate APP_KEY
          working-directory: backend
          run: |
            echo "APP_KEY=" > .env
            php artisan key:generate --force

        - name: Run tests
          working-directory: backend
          run: php artisan test